### ISSUE TITLE
Empty sequence when iterated until end

### ISSUE THREAD

**Issue by gmelodie** [nathan-cruz77/float_range#15]
The test_min_max does not work, instead it gives

```
Traceback (most recent call last):
  File "tests/test_range.py", line 22, in test_min_max
    max(seq)
ValueError: max() arg is an empty sequence
```

Thus it seems that this happens not only with min and max functions, but every time a FloatRange object is iterated until it's end.

**Comment by nathan-cruz77** [comment]
Fixed by https://github.com/nathan-cruz77/float_range/pull/24.
